# Generated by Django 5.0.2 on 2024-02-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_itemsall_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_calorie',
        ),
    ]
