# Generated by Django 5.0.2 on 2024-02-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_calorie',
            new_name='BMR',
        ),
    ]
