# Generated by Django 5.0.2 on 2024-02-17 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_itemsall_calorie_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsall',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
