# Generated by Django 5.0.2 on 2024-02-17 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_itemsall_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsall',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
